### ISSUE TITLE
Passing `date` doesn't work

### ISSUE THREAD

**Issue by dv** [the-refinery/sparkpost_rails#40]
Doing this:
```ruby
mail(subject: subject, sparkpost_data: {transactional: false, date: time})
```
Gives us this error:
```
SyntaxError: (eval):1: syntax error, unexpected tCONSTANT, expecting =>
{:transactional=>false, :date=>Sat, 13 May 2017 12:10:15 UTC +00:00}
                                          ^
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sparkpost_rails-1.4.0/lib/sparkpost_rails/delivery_method.rb:46:in `eval'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sparkpost_rails-1.4.0/lib/sparkpost_rails/delivery_method.rb:46:in `find_sparkpost_data_from'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sparkpost_rails-1.4.0/lib/sparkpost_rails/delivery_method.rb:14:in `deliver!'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mail-2.6.5/lib/mail/message.rb:253:in `deliver!'
	from /Users/david/.rbenv/versions/2.3.1/lib/ruby/2.3.0/delegate.rb:83:in `method_missing'
```

Looks like the time gets converted to a string which is then subsequently not parsable by `eval`:

```
[3] pry(#<SparkPostRails::DeliveryMethod>)> mail[:sparkpost_data]
=> #<Mail::Field 0x7f9d7e8891e0 @name="sparkpost-data" @value={:transactional=>false, :date=>Sat, 13 May 2017 12:10:37 UTC +00:00} @raw_value=nil @charset="UTF-8" @field_order_id=100 @field=#<Mail::OptionalField:0x007f9d6352a4b0 @errors=[], @charset="UTF-8", @name="sparkpost-data", @length=nil, @tree=nil, @element=nil, @value="{:transactional=>false, :date=>Sat, 13 May 2017 12:10:37 UTC +00:00}">>
```

**Comment by dv** [comment]
Never mind, I added it to `sparkpost_data` while it's just a `mail` argument - this fixed it.
